task: detection

evaluator: 
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 2
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset:  
    type: CocoDetection
    img_folder: ../dataset/VisDrone/VisDrone2019-VID-train/sequences/
    ann_file: ../dataset/VisDrone/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion

val_dataloader:
  type: DataLoader
  dataset:   
    type: CocoDetection
    img_folder: ../dataset/VisDrone/VisDrone2019-VID-val/sequences/
    ann_file: ../dataset/VisDrone/val.json
    return_masks: False
    transforms:
      type: Compose
      ops:  ~ 
  shuffle: False
  num_workers: 4
  drop_last: True
  collate_fn:
    type:  BatchImageCollateFuncion